server:
  port: 8081
  servlet:
    context-path: /chatapp
spring:
  application:
    name: chatApp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chatapp
    username: root
    password: bac22111

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

jwt:
  secretKey: XUKBnfAjVfpq5y8d8zLLkiL96aQ2ljj9/9QkD2x37D1039noLGaD3AqrYJautX5NIt2PjjtkJAaHfl13+wEngg==